services:
  - type: web
    name: netproinfotech
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn netproinfotech.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "netproinfotech.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: netproinfotech-db
          property: connectionString
  - type: pserv
    name: netproinfotech-db
    ipWhitelist: []
    plan: free
    postgresVersion: 15
